In [24]:
from pyts.datasets import load_basic_motions

import numpy as np

from rfcm import RFCM

In [6]:
class TimeSeries:
    def __init__(self, data: list):
        self.data = np.array(data)
    
    def __add__(self, other):
        if isinstance(other, TimeSeries):
            return TimeSeries(self.data + other.data)
        elif isinstance(other, int):
            return TimeSeries(self.data + other)
        elif isinstance(other, float):
            return TimeSeries(self.data + other)
        elif isinstance(other, np.ndarray):
            return TimeSeries(self.data + other)
        
    def __radd__(self, other):
        return self + other
        
    def __sub__(self, other):
        if isinstance(other, TimeSeries):
            return TimeSeries(self.data - other.data)
        elif isinstance(other, int):
            return TimeSeries(self.data - other)
        elif isinstance(other, float):
            return TimeSeries(self.data - other)
        elif isinstance(other, np.ndarray):
            return TimeSeries(self.data - other)
    
    def __rsub__(self, other):
        return -self + other
    
    def __mul__(self, other):
        if isinstance(other, TimeSeries):
            return TimeSeries(self.data * other.data)
        elif isinstance(other, int):
            return TimeSeries(self.data * other)
        elif isinstance(other, float):
            return TimeSeries(self.data * other)
        elif isinstance(other, np.ndarray):
            return TimeSeries(self.data * other)
    
    def __rmul__(self, other):
        return self * other
        
    def __truediv__(self, other):
        if isinstance(other, TimeSeries):
            return TimeSeries(self.data / other.data)
        elif isinstance(other, int):
            return TimeSeries(self.data / other)
        elif isinstance(other, float):
            return TimeSeries(self.data / other)
        elif isinstance(other, np.ndarray):
            return TimeSeries(self.data / other)
    
    def __floordiv__(self, other):
        if isinstance(other, TimeSeries):
            return TimeSeries(self.data // other.data)
        elif isinstance(other, int):
            return TimeSeries(self.data // other)
        elif isinstance(other, float):
            return TimeSeries(self.data // other)
        elif isinstance(other, np.ndarray):
            return TimeSeries(self.data // other)
        
    def __pow__(self, other):
        if isinstance(other, TimeSeries):
            return TimeSeries(self.data ** other.data)
        elif isinstance(other, int):
            return TimeSeries(self.data ** other)
        elif isinstance(other, float):
            return TimeSeries(self.data ** other)
        elif isinstance(other, np.ndarray):
            return TimeSeries(self.data ** other)
    
    def __neg__(self):
        return TimeSeries(-self.data)
    
    def __repr__(self):
        return str(self.data)
    
    def __len__(self):
        return len(self.data)
    
    def append(self, other):
        self.data = np.append(self.data, other)
        return self
    
    def extend(self, other):
        self.data = np.append(self.data, other.data)
        return self
    
    def size(self):
        return len(self.data)
    
    def get_data(self):
        return self.data

In [20]:
bunch = load_basic_motions()

In [22]:
bunch.data_train

array([[[ 7.910600e-02,  7.910600e-02, -9.034970e-01, ...,
         -1.932710e-01, -1.932710e-01, -2.051500e-01],
        [ 3.940320e-01,  3.940320e-01, -3.666397e+00, ...,
          5.522700e-02,  5.522700e-02, -3.390000e-03],
        [ 5.514440e-01,  5.514440e-01, -2.828440e-01, ...,
         -4.153000e-02, -4.153000e-02, -1.511300e-02],
        [ 3.515650e-01,  3.515650e-01, -9.588100e-02, ...,
          0.000000e+00,  0.000000e+00, -7.990000e-03],
        [ 2.397000e-02,  2.397000e-02, -3.196050e-01, ...,
         -1.331700e-02, -1.331700e-02, -1.065300e-02],
        [ 6.338830e-01,  6.338830e-01,  9.721310e-01, ...,
         -6.392100e-02, -6.392100e-02, -3.196000e-02]],

       [[ 3.777510e-01,  3.777510e-01,  2.952965e+00, ...,
         -3.233830e-01, -3.336250e-01, -3.336250e-01],
        [-6.108500e-01, -6.108500e-01,  9.707170e-01, ...,
         -9.859300e-02, -2.159870e-01, -2.159870e-01],
        [-1.473760e-01, -1.473760e-01, -5.962515e+00, ...,
          6.305100e-02, -8.

In [25]:
model = RFCM(n_clusters=3)
model.fit(bunch.data_train)

----- Start size insensitive rfcm -----
Convergence in 7 iterations, difference is 0.4520571287648398
----- Start noise resistant rfcm -----
Convergence in 3 iterations, difference is 0.21709520208794272


RFCM(n_clusters=3)

In [26]:
model.labels_

array([2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [4]:
bunch.data_train

array([[[ 7.910600e-02,  7.910600e-02, -9.034970e-01, ...,
         -1.932710e-01, -1.932710e-01, -2.051500e-01],
        [ 3.940320e-01,  3.940320e-01, -3.666397e+00, ...,
          5.522700e-02,  5.522700e-02, -3.390000e-03],
        [ 5.514440e-01,  5.514440e-01, -2.828440e-01, ...,
         -4.153000e-02, -4.153000e-02, -1.511300e-02],
        [ 3.515650e-01,  3.515650e-01, -9.588100e-02, ...,
          0.000000e+00,  0.000000e+00, -7.990000e-03],
        [ 2.397000e-02,  2.397000e-02, -3.196050e-01, ...,
         -1.331700e-02, -1.331700e-02, -1.065300e-02],
        [ 6.338830e-01,  6.338830e-01,  9.721310e-01, ...,
         -6.392100e-02, -6.392100e-02, -3.196000e-02]],

       [[ 3.777510e-01,  3.777510e-01,  2.952965e+00, ...,
         -3.233830e-01, -3.336250e-01, -3.336250e-01],
        [-6.108500e-01, -6.108500e-01,  9.707170e-01, ...,
         -9.859300e-02, -2.159870e-01, -2.159870e-01],
        [-1.473760e-01, -1.473760e-01, -5.962515e+00, ...,
          6.305100e-02, -8.

In [19]:
X = bunch.data_train

a = []
for x in X:
    b = []
    for y in x:
        b.append(TimeSeries(y))
    a.append(b)

a = np.array(a)
a.shape

(40, 6)

In [16]:
with np.nditer(X, op_flags=['readwrite']) as it:
    for x in it:
        x[...] = TimeSeries(x)
        
X

TypeError: float() argument must be a string or a real number, not 'TimeSeries'